eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://10.43.100.223:8761/eureka}
    # To report to Eureka when this service is up discovery-service
    registerWithEureka: true
  instance:
    ip-address: 10.43.101.44
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
